 select 
     V_40_STR org_code , V_300_STR org_name ,  V_20_STR org_pk    ,  
     sum(fa_value_begin) fa_value_begin , 
     sum(fa_value_begin_machine) fa_value_begin_machine ,
     sum(fa_value_begin_building) fa_value_begin_building ,
     sum(fa_value_begin_vehicle) fa_value_begin_vehicle ,
     sum(fa_value_begin_other) fa_value_begin_other , 
     sum(fa_accu_dep_begin) fa_accu_dep_begin , 
     sum(fa_accu_dep_begin_machine) fa_accu_dep_begin_machine ,
     sum(fa_accu_dep_begin_building) fa_accu_dep_begin_building ,
     sum(fa_accu_dep_begin_vehicle) fa_accu_dep_begin_vehicle ,
     sum(fa_accu_dep_begin_other) fa_accu_dep_begin_other , 
     sum(fa_value_add) fa_value_add  ,
     sum(fa_accu_dep_add) fa_accu_dep_add  , 
     sum(fa_value_add_purchase) fa_value_add_purchase , 
     sum(fa_value_add_purchase_machine) fa_value_add_purchase_machine,
     sum(fa_value_add_purchase_building) fa_value_add_purchase_building,
     sum(fa_value_add_purchase_vehicle) fa_value_add_purchase_vehicle,
     sum(fa_value_add_purchase_other) fa_value_add_purchase_other, 
     sum(fa_accu_dep_add_purchase) fa_accu_dep_add_purchase , 
     sum(fa_accu_dep_add_pur_machine) fa_accu_dep_add_pur_machine , 
     sum(fa_accu_dep_add_pur_building) fa_accu_dep_add_pur_building , 
     sum(fa_accu_dep_add_pur_vehicle) fa_accu_dep_add_pur_vehicle , 
     sum(fa_accu_dep_add_pur_other) fa_accu_dep_add_pur_other , 
         
     sum(fa_value_add_constructure) fa_value_add_constructure  , 
     sum(fa_value_add_cons_mechine)  fa_value_add_cons_mechine  ,  
     sum(fa_value_add_cons_building)  fa_value_add_cons_building  ,  
     sum(fa_value_add_cons_vehicle)  fa_value_add_cons_vehicle  , 
     sum(fa_value_add_cons_other)  fa_value_add_cons_other  ,   
                 
     sum(fa_accu_dep_add_constructure) fa_accu_dep_add_constructure,
     sum(fa_accu_dep_add_cons_machine)  fa_accu_dep_add_cons_machine,
     sum(fa_accu_dep_add_cons_building) fa_accu_dep_add_cons_building,
     sum(fa_accu_dep_add_cons_vehicle) fa_accu_dep_add_cons_vehicle,
     sum(fa_accu_dep_add_cons_other) fa_accu_dep_add_cons_other,
             
             
     sum(fa_value_add_other) fa_value_add_other  ,  
     sum(fa_value_add_other_machine) fa_value_add_other_machine  ,
     sum(fa_value_add_other_building)  fa_value_add_other_building  ,
     sum(fa_value_add_other_vehicle)  fa_value_add_other_vehicle  ,
     sum(fa_value_add_other_other)  fa_value_add_other_other  ,
             
     sum(fa_accu_dep_add_other) fa_accu_dep_add_other, 
     sum(fa_accu_dep_add_other_machine) fa_accu_dep_add_other_machine, 
     sum(fa_accu_dep_add_other_building) fa_accu_dep_add_other_building, 
     sum(fa_accu_dep_add_other_vehicle) fa_accu_dep_add_other_vehicle, 
     sum(fa_accu_dep_add_other_other) fa_accu_dep_add_other_other, 
             
     sum(fa_value_reduce) fa_value_reduce ,
     sum(fa_accu_dep_reduce)fa_accu_dep_reduce ,
             
     sum(fa_value_reduce_useless)  fa_value_reduce_useless , 
     sum(fa_value_red_useless_machine)  fa_value_red_useless_machine ,
     sum(fa_value_red_useless_building)  fa_value_red_useless_building , 
     sum(fa_value_red_useless_vehicle)  fa_value_red_useless_vehicle , 
     sum(fa_value_red_useless_other)  fa_value_red_useless_other , 
             
     sum(fa_accu_dep_reduce_useless) fa_accu_dep_reduce_useless , 
     sum(fa_accu_dep_red_ul_machine) fa_accu_dep_red_ul_machine , 
     sum(fa_accu_dep_red_ul_building) fa_accu_dep_red_ul_building ,
     sum(fa_accu_dep_red_ul_vehicle) fa_accu_dep_red_ul_vehicle ,
     sum(fa_accu_dep_red_ul_other) fa_accu_dep_red_ul_other ,
             
             
     sum(fa_value_reduce_other) fa_value_reduce_other, 
     sum(fa_value_red_other_machine) fa_value_red_other_machine,
     sum(fa_value_red_other_building) fa_value_red_other_building,
     sum(fa_value_red_other_vehicle) fa_value_red_other_vehicle,
     sum(fa_value_red_other_other) fa_value_red_other_other, 
             
     sum(fa_accu_dep_reduce_other) fa_accu_dep_reduce_other, 
     sum(fa_accu_dep_red_other_machine) fa_accu_dep_red_other_machine, 
     sum(fa_accu_dep_red_other_building) fa_accu_dep_red_other_building, f
     sum(fa_accu_dep_red_other_vehicle) fa_accu_dep_red_other_vehicle, 
     sum(fa_accu_dep_red_other_other) fa_accu_dep_red_other_other, 
             
     sum(fa_value_end) fa_value_end  , 
     sum(fa_value_end_machine) fa_value_end_machine ,
     sum(fa_value_end_building) fa_value_end_building ,
     sum(fa_value_end_vehicle) fa_value_end_vehicle ,
     sum(fa_value_end_other) fa_value_end_other ,
     sum(fa_accu_dep_end) fa_accu_dep_end  ,
     sum(fa_accu_dep_end_machine) fa_accu_dep_end_machine ,
     sum(fa_accu_dep_end_building) fa_accu_dep_end_building ,
     sum(fa_accu_dep_end_vehicle) fa_accu_dep_end_vehicle ,
     sum(fa_accu_dep_end_other) fa_accu_dep_end_other   , 
     
     sum(fa_curr_dep_end)  fa_curr_dep_end , 
     sum(fa_curr_dep_end_machine) fa_curr_dep_end_machine ,
     sum(fa_curr_dep_end_building) fa_curr_dep_end_building ,
     sum(fa_curr_dep_end_vehicle) fa_curr_dep_end_vehicle ,
     sum(fa_curr_dep_end_other) fa_curr_dep_end_other   
   from fa_total  ;
